package com.kooloco.constant;

/**
 * Created by hlink on 18/1/18.
 */

public enum EventBusAction {
    ACCEPTREFRESE,PENDINGREFRESE,NOTIFICATIONVISITOR,NOTIFICATIONLOCAL,UPDATELIST,ORDERDETAILSLOCAL,ORDERDETAILSVISITOR, RECENTCHATUPDATE, UPDATELISTLOCAL,UPDATEORG,LOCALEXPADD, NOTIFICATIONEXPAPPROVE, NOTIFICATIONEXPREJEXT, LOCALEXPSTEP, VISITORSELECTSECONDTAB,VISITORSELECTSECONDTABFILTER,NOTIFICATIONCOUNTDISPLAYVISITOR,NOTIFICATIONCOUNTDISPLAYLOCAL,NOTIFICATIONCOUNTUIVISITOR,NOTIFICATIONCOUNTUILOCAL, FAVREFRESE, SETADDPAYMENTRULES,FAVLISTUPDATE
}
